# Via: https://stackoverflow.com/questions/73667886/how-read-the-secrets-from-another-repo-to-my-repo-using-github-actions/73670069#73670069

name: Reveal secrets
on: workflow_dispatch

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Show secrets
        run: |
          echo ${{secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_SAND_0262EB603}} | base64
